[package]
name = "rust-tracer"
version = "0.1.0"
authors = ["geovani"]
edition = "2018"

[lib]
name = "rust_tracer"
path = "src/lib.rs"
doctest = false

[dependencies]
png = "0.16.8"
chrono = "0.4.19"
derive_builder = "0.9.0"
rand = "0.8.3"
rayon = "1.5.0"
indicatif = "0.15.0"
pad = "0.1.6"
